
local cfg = {}


cfg.groups = {
	["dev"] = {
        "dev.menu",
        "dev.spawncar",
        "dev.spawnweapon",
        "dev.deletecar",
        "dev.fixcar",
		"dev.givemoney",
		"dev.tp2coords",
	    "dev.getcoords",
		"cardev.menu",
		"chat.announce",
		"admin.addcar",
		"admin.spawnGun",
        "admin.menu",
        "admin.warn",
		"admin.vehmenu",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.idsabovehead",
		"admin.noclip",
		"admin.managecommunitypot",
		"admin.moneymenu",
		"admin.staffblips",
		
			
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",

		"group.add.vip",
        "group.add.founder",
        "group.add.operationsmanager",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.founder",
        "group.remove.operationsmanager",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
	},
	["founder"] = {
		
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.vehmenu",
		"admin.spawnGun",
		"admin.addcar",
		"admin.idsabovehead",
		"admin.smartsigns",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",
		"admin.managecommunitypot",
		"admin.moneymenu",
		"admin.staffblips",

		"group.add.vip",
        "group.add.founder",
        "group.add.operationsmanager",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.founder",
        "group.remove.operationsmanager",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		
		"vehicle.delete",
		"chat.announce",
		"cardev.menu",
	},
	["operationsmanager"] = {
        "dev.menu",
        "dev.spawncar",
        "dev.spawnweapon",
        "dev.deletecar",
        "dev.fixcar",
		"dev.tp2coords",
	    "dev.getcoords",
		"admin.special",
		"cardev.menu",
		"chat.announce",


		"admin.addcar",
		"admin.spawnGun",
        "admin.menu",
        "admin.warn",
		"admin.vehmenu",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.idsabovehead",
		"admin.noclip",
		"admin.managecommunitypot",
		"admin.staffblips",
		
			
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",

		"group.add.vip",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
	},
	["staffmanager"] = {
		"dev.menu",
        "dev.spawncar",
        "dev.deletecar",
        "dev.fixcar",
		"dev.tp2coords",
	    "dev.getcoords",
		"admin.vehmenu",
		"admin.special",
		"admin.managecommunitypot",
		"admin.staffblips",
		
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
		"admin.addcar",
        "admin.screenshot",
        "admin.slap",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
		"admin.managecommunitypot",
    	"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"cardev.menu",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.nhsAddGroups",
		"group.add.vip",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		"chat.announce",
	},
	["commanager"] = {
		
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.addcar",
		"admin.freeze",
		"admin.getgroups",
		"admin.spectate",
		"admin.screenshot",
		"admin.slap",
		"admin.staffblips",
		"admin.givemoney",
		"admin.tp2waypoint",
		"admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.nhsAddGroups",

        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		"chat.announce",
	  },
	["headadmin"] = {
		
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.spectate",
		"admin.screenshot",
		"admin.slap",
		"admin.tp2waypoint",
		"admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
		"admin.staffblips",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.nhsAddGroups",
		"admin.donoAddGroups",

		
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		
		"admin.whitelisted",
		"admin.tickets",
		"chat.announce",
  },
  ["senioradmin"] = {
	
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.spectate",
		"admin.screenshot",
		"admin.slap",
		"admin.tp2waypoint",
		"admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		
		"admin.whitelisted",
		"admin.tickets",
  },
  ["administrator"] = {
	
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.spectate",
		"admin.screenshot",
		"admin.slap",
		"admin.tp2waypoint",
		"admin.tp2coords",
		"admin.noclip",

		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
  },
  ["srmoderator"] = {
	
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.screenshot",
		"admin.spectate",

		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
    },
  ["moderator"] = {
	
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.screenshot",
		"admin.spectate",

		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		
  },
  ["supportteam"] = {
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.kick",
		"admin.spectate",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"admin.ban",
		
  },
  ["trialstaff"] = {
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.kick",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		
  },

  ["cardev"] = {
	"cardev.menu",
  },

  -- [Police Groups]
  ["Commissioner Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
      onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setPolice(player, {false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
	"police.putinveh",
	"cop.glock",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"commissioner.paycheck",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"com.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
	"police.maxarmour",
	"police.loadshop2",
  },

  ["Commissioner"] = {
    "commissioner.clockon",
	"cop.whitelisted",
  },

  ["Deputy Commissioner Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
      onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
	"police.getoutveh",
	"deputycommissioner.paycheck",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
	"police.seize.weapons",
	"cop.glock",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"depcom.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
	"police.maxarmour",
	"police.loadshop2",
  },

  ["Deputy Commissioner"] = {
    "depcommissioner.clockon",
	"cop.whitelisted",
  },

  ["Assistant Commissioner Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
      onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
	"police.putinveh",
	"assistantcommissioner.paycheck",
    "police.getoutveh",
	"police.service",
	"cop.glock",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"assistcom.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
	"police.maxarmour",
	"police.loadshop2",
  },

  ["Assistant Commissioner"] = {
    "asscommissioner.clockon",
	"cop.whitelisted",
  },

  ["Deputy Assistant Commissioner Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
      onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
	"police.getoutveh",
	"assistantdeputycommissioner.paycheck",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"cop.glock",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"depassist.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
	"police.maxarmour",
	"police.loadshop2",
  },

  ["Deputy Assistant Commissioner"] = {
    "depasscommissioner.clockon",
	"cop.whitelisted",
  },

  ["Commander Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
      onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"commander.paycheck",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"cop.glock",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"com.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
	"police.maxarmour",
	"police.loadshop2",
  },

  ["Commander"] = {
    "commander.clockon",
	"cop.whitelisted",
  },

  ["Chief Superintendent Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
      onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
	"police.putinveh",
	"chiefsuperintendent.paycheck",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
	"police.seize.items",
	"cop.glock",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"chiefsupt.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
	"police.maxarmour",
  },

  ["Chief Superintendent"] = {
    "chiefsupint.clockon",
	"cop.whitelisted",
  },

  ["Superintendent Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
      onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
	"cop.glock",
	"police.wanted",
	"superintendent.paycheck",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"supt.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
	"police.maxarmour",
  },

  ["Superintendent"] = {
    "superint.clockon",
	"cop.whitelisted",
  },

  ["Chief Inspector Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
      onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
	"police.service",
	"chiefinspector.paycheck",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
	"cop.glock",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"chiefinspector.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Chief Inspector"] = {
    "chiefinsp.clockon",
	"cop.whitelisted",
  },

  ["Inspector Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
      onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"inspector.paycheck",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
	"cop.glock",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"inspector.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Inspector"] = {
    "inspector.clockon",
	"cop.whitelisted",
  },

  ["Sergeant Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
      onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"sergeant.paycheck",
	"police.easy_unjail",
	"cop.glock",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"sergeant.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Sergeant"] = {
    "sgt.clockon",
	"cop.whitelisted",
  },

  ["Special Constable Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
      onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"cop.glock",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
	"police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"spc.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Special Constable"] = {
    "specialpc.clockon",
	"cop.whitelisted",
  },

  ["Senior Constable Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
      onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
	"police.wanted",
	"cop.glock",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
	"police.announce",
	"spc.paycheck",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"seniorpc.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Senior Constable"] = {
    "srpc.clockon",
	"cop.whitelisted",
  },

  ["Police Constable Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
      onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"cop.glock",
	"response.armor",
	"policeconstable.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Police Constable"] = {
    "pc.clockon",
	"cop.whitelisted",
  },

  ["PCSO Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) ARMAclient.setPolice(player, {true}) end,
	  onspawn = function(player) ARMAclient.setPolice(player, {true}) end,
	  onleave = function(player)
		local user_id = ARMA.getUserId(player)  		
		ARMAclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"cop.glock",
	"pcso.armor",
	"pcso.paycheck",
	"police.menu_interaction",
	"police.onduty.permission",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["PCSO"] = {
    "pcso.clockon",
	"cop.whitelisted",
  },

  ["Head Chief Medical Officer Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Assistant Chief Medical Officer Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Deputy Chief Medical Officer Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Captain Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Consultant Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Specialist Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Senior Doctor Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Junior Doctor Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Critical Care Paramedic Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Paramedic Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Trainee Paramedic Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  --[[ NHS Clock On Groups ]]--
  ["Head Chief Medical Officer"] = {
    "hcmo.clockon",
	"clockon.nhs",
  },

  ["Assistant Chief Medical Officer"] = {
    "acmo.clockon",
	"clockon.nhs",
  },

  ["Deputy Chief Medical Officer"] = {
    "dcmo.clockon",
	"clockon.nhs",
  },

  ["Captain"] = {
    "capt.clockon",
	"clockon.nhs",
  },

  ["Consultant"] = {
    "consultant.clockon",
	"clockon.nhs",
  },

  ["Specialist"] = {
    "specialist.clockon",
	"clockon.nhs",
  },

  ["Senior Doctor"] = {
    "srdoctor.clockon",
	"clockon.nhs",
  },

  ["Junior Doctor"] = {
    "jrdoctor.clockon",
	"clockon.nhs",
  },

  ["Critical Care Paramedic"] = {
    "ccp.clockon",
	"clockon.nhs",
  },

  ["Paramedic"] = {
    "paramedic.clockon",
	"clockon.nhs",
  },

  ["Trainee Paramedic"] = {
    "tparamedic.clockon",
	"clockon.nhs",
  },

-- ILLEGAL LICENSES --
  ["Weed"] = {
    "weed.job",
  },
  ["Cocaine"] = {
    "cocaine.job",
  },
  ["Heroin"] = {
    "heroin.job",
  },
  ["LSD"] = {
    "lsd.job",
  },

-- LEGAL LICENSES --
  ["Scrap"] = {
    "scrap.job",
  },
  ["Gold"] = {
    "gold.job",
  },
  ["Diamond"] = {
    "diamond.job",
  },

-- HOUR REWARDS --
  ["10hrs"] = {},
  ["25hrs"] = {},
  ["50hrs"] = {},
  ["100hrs"] = {},
  ["250hrs"] = {},
  ["500hrs"] = {},

  ["Gang"] = {
    "gang.whitelist",
  },
  ["highroller"] = {
    "casino.highrollers",
  },

  ["Rebel"] = {
    "rebellicense.whitelisted",
  },
  ["AdvancedRebel"] = {
    "advancedrebel.license",
  },

-- DONATOR GROUPS --
  ["Supporter"] = {
  	"vip.gunstore",
  },  
  ["Platinum"] = {
  	"vip.gunstore",
  },  
  ["Godfather"] = {
  	"vip.gunstore",
  },  
  ["Underboss"] = {
  	"vip.gunstore",
  },

-- POV GROUP --
  ["pov"] = {
  	"pov.list"
  },

  ["DJ"] = {
	"dj.menu"
  },
  ["PilotLicense"] = {
	"air.whitelisted"
  },
  
  ["TutorialDone"] = {},
  ["polblips"] = {},

  -- Default Jobs
  ["AA Mechanic"] = {},
  ["Royal Mail Driver"] = {},
  ["Bus Driver"] = {},
  ["Deliveroo"] = {},
  ["Fisherman"] = {},
  ["Scuba Diver"] = {},
  ["Pilot"] = {},
  ["G4S Driver"] = {},
  ["Lorry Driver"] = {},
  ["Taco Seller"] = {},
  ["Burger Shot Cook"] = {},

}

-- groups are added dynamically using the API or the menu, but you can add group when an user join here
cfg.users = {
}

-- group selectors
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {}

return cfg
