local cfg = {}

--!Class Types
--AR - 7.5kg
--SMG - 5kg
--Shotgun - 7.5kg
--Pistol - 2.5KG
--Heavy - 10KG
--Melee - 1KG

--todo change all WT_HASH to same as WEAPON_HASH

cfg.weapons = {
    --? Melees
    ["GADGET_PARACHUTE"] = {
        name = "Parachute",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "",
        weight = 2.5,
    },
    ["WEAPON_STUNGUN"] = {
        name = "Tazer",
        class = "Melee", --So that it can be equipped with a pistol.
        ammo = "modelammo",
        policeWeapon = true,
        model = "",
        weight = 2.5,
    },
    ["WEAPON_FLASHLIGHT"] = {
        name = "Flashlight",
        class = "Melee",
        ammo = "modelammo",
        policeWeapon = false,
        model = "",
        weight = 2.5,
    },
    ["WEAPON_NIGHTSTICK"] = {
        name = "Police Baton",
        class = "Melee",
        ammo = "modelammo",
        policeWeapon = true,
        model = "",
        weight = 2.5,
    },
    ["WEAPON_MJOLNIR"] = {
        name = "Mjolnir",
        class = "Melee",
        ammo = "modelammo",
        policeWeapon = false,
        model = "w_me_mjolnir",
        weight = 10,
    },
    ["WEAPON_MOLOTOV"] = {
        name = "Molotov",
        class = "Melee",
        ammo = "modelammo",
        policeWeapon = false,
        model = "",
    },
    ["WEAPON_SMOKEGRENADE"] = {
        name = "Smoke Grenade",
        class = "Melee",
        ammo = "",
        policeWeapon = true,
        model = "",
        weight = 2.5,
    },
    ["WEAPON_SNOWBALL"] = {
        name = "Snowball",
        class = "Melee",
        ammo = "modelammo",
        policeWeapon = false,
        model = "",
    },
    ["WEAPON_FLASHBANG"] = {
        name = "Flashbang",
        class = "Melee",
        ammo = "modelammo",
        policeWeapon = true,
        model = "",
        weight = 2.5,
    },
    ["WEAPON_STAFFGUN"] = {
        name = "ARMA Staff Gun",
        class = "Pistol",
        ammo = "",
        policeWeapon = true,
        model = "",
        weight = 2.5,
    },
    ["WEAPON_FORRESTAX"] = {
        name = "The Forrest Axe",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_forrestax",
        weight = 1.0,
    },
    ["WEAPON_SKULLCLUB"] = {
        name = "Skull Club",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_skullclub",
        weight = 1.0,
    },
    ["WEAPON_SLEDGESHAMMER"] = {
        name = "Sledges Hammer",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_sledgeshammer",
        weight = 1.0,
    },
    ["WEAPON_CLIMBINGAXE"] = {
        name = "Climbing Axe",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_climbingaxe",
        weight = 1.0,
    },
    ["WEAPON_CRAFTEDAXE"] = {
        name = "Crafted Axe",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_craftedaxe",
        weight = 1.0,
    },
    ["WEAPON_BROOM"] = {
        name = "Broom",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_broom",
        weight = 2.5,
    },
    ["WEAPON_CLEAVER"] = {
        name = "Cleaver",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_cleaver",
        weight = 2.5,
    },
    ["WEAPON_CRICKETBAT"] = {
        name = "Cricket Bat",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_cricketbat",
        weight = 2.5,
    },
    ["WEAPON_DILDO"] = {
        name = "Pink Dildo",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_dildo",
        weight = 2.5,
    },
    ["WEAPON_FIREAXE"] = {
        name = "Fireaxe",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_fireaxe",
        weight = 2.5,
    },
    ["WEAPON_GUITAR"] = {
        name = "Guitar",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_guitar",
        weight = 2.5,
    },
    ["WEAPON_KITCHENKNIFE"] = {
        name = "Kitchen Knife",
        class = "Pistol",
        ammo = "",
        policeWeapon = false,
        model = "w_me_kitchenknife",
        weight = 2.5,
    },
    ["WEAPON_SHANK"] = {
        name = "Wooden Shank",
        class = "Pistol",
        ammo = "",
        policeWeapon = false,
        model = "w_me_shank",
        weight = 2.5,
    },
    ["WEAPON_SHOVEL"] = {
        name = "Shovel",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_shovel",
        weight = 2.5,
    },
    ["WEAPON_SLEDGEHAMMER"] = {
        name = "Sledgehammer",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_sledgehammer",
        weight = 2.5,
    },
    ["WEAPON_TRAFFICSIGN"] = {
        name = "Traffic Sign",
        class = "Melee",
        ammo = "",
        policeWeapon = false,
        model = "w_me_trafficsign",
        weight = 2.5,
    },
    --? pistols
    ["WEAPON_PDGLOCK"] = {
        name = "Glock",
        class = "Pistol",
        ammo = "Police Issued 9mm",
        policeWeapon = true,
        model = "w_pi_glock",
        weight = 2.5,
    },
    ["WEAPON_BERETTA"] = {
        name = "Beretta",
        class = "Pistol",
        ammo = "9mm Bullets",
        policeWeapon = false,
        model = "w_pi_beretta",
        weight = 2.5,
    },
    ["WEAPON_FNX"] = {
        name = "FNX",
        class = "Pistol",
        ammo = "9mm Bullets",
        policeWeapon = false,
        model = "w_pi_fnx",
        weight = 2.5,
    },
    ["WEAPON_TX22"] = {
        name = "TX22",
        class = "Pistol",
        ammo = "9mm Bullets",
        policeWeapon = false,
        model = "w_pi_fnx",
        weight = 2.5,
    },
    ["WEAPON_PYTHON"] = {
        name = "Python",
        class = "Pistol",
        ammo = ".357 Bullets",
        policeWeapon = false,
        model = "w_pi_python",
        weight = 2.5,
    },
    --? ARs
    ["WEAPON_GOLDAK"] = {
        name = "Golden AK-47",
        class = "AR",
        ammo = "7.62mm Bullets",
        policeWeapon = false,
        model = "w_ar_goldak",
        weight = 7.5,
    },
    ["WEAPON_SPAR16"] = {
        name = "Spar 16",
        class = "AR",
        ammo = "5.56mm NATO",
        policeWeapon = false,
        model = "w_ar_spar16",
        weight = 7.5,
    },
    ["WEAPON_VAL"] = {
        name = "AS VAL",
        class = "AR",
        ammo = "5.56mm NATO",
        policeWeapon = false,
        model = "w_ar_val",
        weight = 7.5,
    },
    ["WEAPON_ELDERFLAME"] = {
        name = "Elderflame",
        class = "AR",
        ammo = "5.56mm NATO",
        policeWeapon = false,
        model = "w_ar_elderflame",
        weight = 7.5,
    },
    ["WEAPON_AR15"] = {
        name = "AR15",
        class = "AR",
        ammo = "5.56mm NATO",
        policeWeapon = false,
        model = "w_ar_ar15",
        weight = 7.5,
    },
    ["WEAPON_PDTX15"] = {
        name = "TX-15 DML",
        class = "AR",
        ammo = "Police Issued 5.56mm",
        policeWeapon = true,
        model = "w_ar_tx15dml",
        weight = 7.5,
    },
    ["WEAPON_MK18SOG"] = {
        name = "MK18SOG",
        class = "AR",
        ammo = "Police Issued 5.56mm",
        policeWeapon = true,
        model = "w_ar_mk18sog",
        weight = 7.5,
    },
    ["WEAPON_PDM4A1"] = {
        name = "M4A1",
        class = "AR",
        ammo = "Police Issued 5.56mm",
        policeWeapon = true,
        model = "w_ar_m4a1",
        weight = 7.5,
    },
    ["WEAPON_SIGMCX"] = {
        name = "SIG MCX",
        class = "AR",
        ammo = "Police Issued 5.56mm",
        policeWeapon = true,
        model = "w_ar_sigmcx",
        weight = 7.5,
    },
    ["WEAPON_SPAR17"] = {
        name = "Spar 17",
        class = "AR",
        ammo = "Police Issued 5.56mm",
        policeWeapon = true,
        model = "w_ar_spar17",
        weight = 7.5,
    },
    --?SMG
    ["WEAPON_MP5"] = {
        name = "MP5",
        class = "SMG",
        ammo = "Police Issued 9mm",
        policeWeapon = true,
        model = "w_sb_mp5",
        weight = 5,
    },
    ["WEAPON_STING"] = {
        name = "Sting 9mm Bullets",
        class = "SMG",
        ammo = "Police Issued 9mm",
        policeWeapon = true,
        model = "w_sb_sting",
        weight = 5,
    },
    ["WEAPON_MPXC"] = {
        name = "MPX",
        class = "SMG",
        ammo = "9mm Bullets",
        policeWeapon = false,
        model = "w_sb_mpxc",
        weight = 5,
    },
    ["WEAPON_UMP45"] = {
        name = "UMP-45",
        class = "SMG",
        ammo = "9mm Bullets",
        policeWeapon = false,
        model = "w_sb_ump45",
        weight = 5,
    },
    ["WEAPON_MAC11"] = {
        name = "MAC11",
        class = "SMG",
        ammo = "9mm Bullets",
        policeWeapon = false,
        model = "w_sb_mac11",
        weight = 5,
    },
    --? shotguns
    ["WEAPON_REMINGTON870"] = {
        name = "Remington870",
        class = "Shotgun",
        ammo = "Police Issued 12 Gauge",
        policeWeapon = true,
        model = "w_sg_remington870",
        weight = 7.5,
    },
    ["WEAPON_WINCHESTER12"] = {
        name = "Winchester 12",
        class = "Shotgun",
        ammo = "12 Gauge Bullets",
        policeWeapon = false,
        model = "w_sg_winchester12",
        weight = 7.5,
    },
    ["WEAPON_SPAZ"] = {
        name = "Spaz 12",
        class = "Shotgun",
        ammo = "12 Gauge Bullets",
        policeWeapon = false,
        model = "w_sg_spaz",
        weight = 7.5,
    },
    ["WEAPON_AA12"] = {
        name = "Assault A12 Shotgun",
        class = "Shotgun",
        ammo = "12 Gauge Bullets",
        policeWeapon = false,
        model = "w_sg_aa12",
        weight = 7.5,
    },
    --? snipers
    ["WEAPON_DILDET"] = {
        name = "Dildet",
        class = "Shotgun",
        ammo = ".308 Sniper Rounds",
        policeWeapon = false,
        model = "w_ar_dildet",
        weight = 10,
    },
    ["WEAPON_MANDO"] = {
        name = "Mandolorain Sniper",
        class = "Shotgun",
        ammo = ".308 Sniper Rounds",
        policeWeapon = false,
        model = "w_ar_mando",
        weight = 10,
    },
    ["WEAPON_AX50"] = {
        name = "AX-50",
        class = "Heavy",
        ammo = "Police Issued .308 Sniper Rounds",
        policeWeapon = true,
        model = "w_sr_ax50",
    },
    ["WEAPON_REMINGTON700"] = {
        name = "Remington700",
        class = "Heavy",
        ammo = "Police Issued .308 Sniper Rounds",
        policeWeapon = true,
        model = "w_sr_remington700",
        weight = 10,
    },
    ["WEAPON_MOSIN"] = {
        name = "Mosin Nagant",
        class = "Shotgun",
        ammo = "7.62mm Bullets",
        policeWeapon = false,
        model = "w_ar_mosin",
        weight = 7.5,
    },
    ["WEAPON_SVD"] = {
        name = "Dragunov SV",
        class = "Heavy",
        ammo = ".308 Sniper Rounds",
        policeWeapon = false,
        model = "w_sr_svd",
        weight = 10,
    },
    ["WEAPON_BARRET"] = {
        name = "Barret",
        class = "Heavy",
        ammo = ".308 Sniper Rounds",
        policeWeapon = false,
        model = "w_sr_barret",
        weight = 10,
    },
    ["WEAPON_MK14"] = {
        name = "MK14",
        class = "Heavy",
        ammo = ".308 Sniper Rounds",
        policeWeapon = false,
        model = "w_sr_mk14",
        weight = 10,
    },
    ["WEAPON_STAC"] = {
        name = "Stac 33",
        class = "Heavy",
        ammo = "Police Issued .308 Sniper Rounds",
        policeWeapon = true,
        model = "w_sr_stac",
        weight = 10,
    },
    ["WEAPON_G36"] = {
        name = "G36C",
        class = "AR",
        ammo = "Police Issued 5.56mm",
        policeWeapon = true,
        model = "w_ar_g36",
        weight = 10,
    },
}


cfg.nativeWeaponModelsToNames = {
    ["WEAPON_PISTOL"] = 'Pistol',
    ["WEAPON_COMBATPISTOL"] = 'Combat Pistol',
    ["WEAPON_APPISTOL"] = 'AP Pistol',
    ["WEAPON_PISTOL50"] = 'Pistol .50',
    ["WEAPON_MICROSMG"] = 'Micro SMG',
    ["WEAPON_SMG"] = 'SMG',
    ["WEAPON_ASSAULTSMG"] = 'Assault SMG',
    ["WEAPON_ASSAULTRIFLE"] = 'Assault Rifle',
    ["WEAPON_CARBINERIFLE"] = 'Carbine Rifle',
    ["WEAPON_ADVANCEDRIFLE"] = 'Advanced Rifle',
    ["WEAPON_MG"] = 'MG',
    ["WEAPON_COMBATMG"] = 'Combat MG',
    ["WEAPON_PUMPSHOTGUN"] = 'Pump Shotgun',
    ["WEAPON_SAWNOFFSHOTGUN"] = 'Sawed-Off Shotgun',
    ["WEAPON_ASSAULTSHOTGUN"] = 'Assault Shotgun',
    ["WEAPON_BULLPUPSHOTGUN"] = 'Bullpup Shotgun',
    ["WEAPON_SNIPERRIFLE"] = 'Sniper Rifle',
    ["WEAPON_HEAVYSNIPER"] = 'Heavy Sniper',
    ["WEAPON_REMOTESNIPER"] = 'Remote Sniper',
    ["WEAPON_GRENADELAUNCHER"] = 'Grenade Launcher',
    ["WEAPON_GRENADELAUNCHER_SMOKE"] = 'Smoke Grenade Launcher',
    ["WEAPON_RPG"] = 'RPG',
    ["WEAPON_PASSENGER_ROCKET"] = 'Passenger Rocket',
    ["WEAPON_AIRSTRIKE_ROCKET"] = 'Airstrike Rocket',
    ["WEAPON_STINGER"] = 'Stinger [Vehicle]',
    ["WEAPON_MINIGUN"] = 'Minigun',
    ["WEAPON_GRENADE"] = 'Grenade',
    ["WEAPON_STICKYBOMB"] = 'Sticky Bomb',
    ["WEAPON_SMOKEGRENADE"] = 'Tear Gas',
    ["WEAPON_BZGAS"] = 'BZ Gas',
    ["WEAPON_MOLOTOV"] = 'Molotov',
    ["WEAPON_FIREEXTINGUISHER"] = 'Fire Extinguisher',
    ["WEAPON_PETROLCAN"] = 'Jerry Can',
    ["OBJECT"] = 'Object',
    ["WEAPON_BALL"] = 'Ball',
    ["WEAPON_FLARE"] = 'Flare',
    ["VEHICLE_WEAPON_TANK"] = 'Tank Cannon',
    ["VEHICLE_WEAPON_SPACE_ROCKET"] = 'Rockets',
    ["VEHICLE_WEAPON_PLAYER_LASER"] = 'Laser',
    ["AMMO_RPG"] = 'Rocket',
    ["AMMO_TANK"] = 'Tank',
    ["AMMO_SPACE_ROCKET"] = 'Rocket',
    ["AMMO_PLAYER_LASER"] = 'Laser',
    ["AMMO_ENEMY_LASER"] = 'Laser',
    ["WEAPON_RAMMED_BY_CAR"] = 'Rammed by Car',
    ["WEAPON_BOTTLE"] = 'Bottle',
    ["WEAPON_GUSENBERG"] = 'Gusenberg Sweeper',
    ["WEAPON_SNSPISTOL"] = 'SNS Pistol',
    ["WEAPON_VINTAGEPISTOL"] = 'Vintage Pistol',
    --["WEAPON_DAGGER"] = 'Antique Cavalry Dagger',
    ["WEAPON_FLAREGUN"] = 'Flare Gun',
    ["WEAPON_HEAVYPISTOL"] = 'Heavy Pistol',
    ["WEAPON_SPECIALCARBINE"] = 'Special Carbine',
    ["WEAPON_MUSKET"] = 'Musket',
    ["WEAPON_FIREWORK"] = 'Firework Launcher',
    ["WEAPON_MARKSMANRIFLE"] = 'Marksman Rifle',
    ["WEAPON_HEAVYSHOTGUN"] = 'Heavy Shotgun',
    ["WEAPON_PROXMINE"] = 'Proximity Mine',
    ["WEAPON_HOMINGLAUNCHER"] = 'Homing Launcher',
    ["WEAPON_HATCHET"] = 'Hatchet',
    ["WEAPON_COMBATPDW"] = 'Combat PDW',
    ["WEAPON_KNUCKLE"] = 'Knuckle Duster',
    ["WEAPON_MARKSMANPISTOL"] = 'Marksman Pistol',
    ["WEAPON_MACHETE"] = 'Machete',
    ["WEAPON_MACHINEPISTOL"] = 'Machine Pistol',
    ["WEAPON_FLASHLIGHT"] = 'Flashlight',
    ["WEAPON_DBSHOTGUN"] = 'Double Barrel Shotgun',
    ["WEAPON_COMPACTRIFLE"] = 'Compact Rifle',
    ["WEAPON_SWITCHBLADE"] = 'Switchblade',
    ["WEAPON_REVOLVER"] = 'Heavy Revolver',
    ["WEAPON_FIRE"] = 'Fire',
    ["WEAPON_HELI_CRASH"] = 'Heli Crash',
    ["WEAPON_RUN_OVER_BY_CAR"] = 'Run over by Car',
    ["WEAPON_HIT_BY_WATER_CANNON"] = 'Hit by Water Cannon',
    ["WEAPON_EXHAUSTION"] = 'Exhaustion',
    ["WEAPON_EXPLOSION"] = 'Explosion',
    ["WEAPON_ELECTRIC_FENCE"] = 'Electric Fence',
    ["WEAPON_BLEEDING"] = 'Bleeding',
    ["WEAPON_DROWNING_IN_VEHICLE"] = 'Drowning in Vehicle',
    ["WEAPON_DROWNING"] = 'Drowning',
    ["WEAPON_BARBED_WIRE"] = 'Barbed Wire',
    ["WEAPON_VEHICLE_ROCKET"] = 'Vehicle Rocket',
    ["WEAPON_BULLPUPRIFLE"] = 'Bullpup Rifle',
    ["WEAPON_ASSAULTSNIPER"] = 'Assault Sniper',
    ["VEHICLE_WEAPON_ROTORS"] = 'Rotors',
    ["WEAPON_RAILGUN"] = 'Railgun',
    ["WEAPON_AIR_DEFENCE_GUN"] = 'Air Defence Gun',
    ["WEAPON_AUTOSHOTGUN"] = 'Automatic Shotgun',
    ["WEAPON_BATTLEAXE"] = 'Battle Axe',
    ["WEAPON_COMPACTLAUNCHER"] = 'Compact Grenade Launcher',
    ["WEAPON_MINISMG"] = 'Mini SMG',
    ["WEAPON_PIPEBOMB"] = 'Pipebomb',
    ["WEAPON_POOLCUE"] = 'Poolcue',
    ["WEAPON_WRENCH"] = 'Wrench',
    ["WEAPON_SNOWBALL"] = 'Snowball',
    ["WEAPON_ANIMAL"] = 'Animal',
    ["WEAPON_COUGAR"] = 'Cougar',
    ["WEAPON_UNARMED"] = "Fists"
}

cfg.illegalNativeWeaponsHashToModels = {
    [`WEAPON_HAMMER`] = 'Hammer',
    [`WEAPON_BAT`] = 'Baseball Bat',
    [`WEAPON_GOLFCLUB`] = 'Golf Club',
    [`WEAPON_CROWBAR`] = 'Crowbar',
    [`WEAPON_PISTOL`] = 'Pistol',
    [`WEAPON_COMBATPISTOL`] = 'Combat Pistol',
    [`WEAPON_APPISTOL`] = 'AP Pistol',
    [`WEAPON_PISTOL50`] = 'Pistol .50',
    [`WEAPON_MICROSMG`] = 'Micro SMG',
    [`WEAPON_SMG`] = 'SMG',
    [`WEAPON_ASSAULTSMG`] = 'Assault SMG',
    [`WEAPON_ASSAULTRIFLE`] = 'Assault Rifle',
    [`WEAPON_CARBINERIFLE`] = 'Carbine Rifle',
    [`WEAPON_ADVANCEDRIFLE`] = 'Advanced Rifle',
    [`WEAPON_MG`] = 'MG',
    [`WEAPON_COMBATMG`] = 'Combat MG',
    [`WEAPON_PUMPSHOTGUN`] = 'Pump Shotgun',
    [`WEAPON_SAWNOFFSHOTGUN`] = 'Sawed-Off Shotgun',
    [`WEAPON_ASSAULTSHOTGUN`] = 'Assault Shotgun',
    [`WEAPON_BULLPUPSHOTGUN`] = 'Bullpup Shotgun',
    [`WEAPON_SNIPERRIFLE`] = 'Sniper Rifle',
    [`WEAPON_HEAVYSNIPER`] = 'Heavy Sniper',
    [`WEAPON_REMOTESNIPER`] = 'Remote Sniper',
    [`WEAPON_GRENADELAUNCHER`] = 'Grenade Launcher',
    [`WEAPON_GRENADELAUNCHER_SMOKE`] = 'Smoke Grenade Launcher',
    [`WEAPON_RPG`] = 'RPG',
    [`WEAPON_STINGER`] = 'Stinger [Vehicle]',
    [`WEAPON_MINIGUN`] = 'Minigun',
    [`WEAPON_GRENADE`] = 'Grenade',
    [`WEAPON_STICKYBOMB`] = 'Sticky Bomb',
    [`WEAPON_BOTTLE`] = 'Bottle',
    [`WEAPON_GUSENBERG`] = 'Gusenberg Sweeper',
    [`WEAPON_SNSPISTOL`] = 'SNS Pistol',
    [`WEAPON_VINTAGEPISTOL`] = 'Vintage Pistol',
    [`WEAPON_HEAVYPISTOL`] = 'Heavy Pistol',
    [`WEAPON_SPECIALCARBINE`] = 'Special Carbine',
    [`WEAPON_MUSKET`] = 'Musket',
    [`WEAPON_FIREWORK`] = 'Firework Launcher',
    [`WEAPON_MARKSMANRIFLE`] = 'Marksman Rifle',
    [`WEAPON_HEAVYSHOTGUN`] = 'Heavy Shotgun',
    [`WEAPON_PROXMINE`] = 'Proximity Mine',
    [`WEAPON_HOMINGLAUNCHER`] = 'Homing Launcher',
    [`WEAPON_HATCHET`] = 'Hatchet',
    [`WEAPON_COMBATPDW`] = 'Combat PDW',
    [`WEAPON_MARKSMANPISTOL`] = 'Marksman Pistol',
    [`WEAPON_MACHINEPISTOL`] = 'Machine Pistol',
    [`WEAPON_DBSHOTGUN`] = 'Double Barrel Shotgun',
    [`WEAPON_COMPACTRIFLE`] = 'Compact Rifle',
    [`WEAPON_REVOLVER`] = 'Heavy Revolver',
    [`WEAPON_VEHICLE_ROCKET`] = 'Vehicle Rocket',
    [`WEAPON_BULLPUPRIFLE`] = 'Bullpup Rifle',
    [`WEAPON_ASSAULTSNIPER`] = 'Assault Sniper',
    [`WEAPON_RAILGUN`] = 'Railgun',
    [`WEAPON_AIR_DEFENCE_GUN`] = 'Air Defence Gun',
    [`WEAPON_AUTOSHOTGUN`] = 'Automatic Shotgun',
    [`WEAPON_BATTLEAXE`] = 'Battle Axe',
    [`WEAPON_COMPACTLAUNCHER`] = 'Compact Grenade Launcher',
    [`WEAPON_MINISMG`] = 'Mini SMG',
    [`WEAPON_PIPEBOMB`] = 'Pipebomb',
    [`WEAPON_POOLCUE`] = 'Poolcue',
    [`WEAPON_WRENCH`] = 'Wrench',
    [`WEAPON_MARKSMANRIFLE_MK2`] = 'Wrench',
    [`WEAPON_PUMPSHOTGUN_MK2`] = 'Wrench',
    [`WEAPON_SPECIALCARBINE_MK2`] = 'Wrench',
    [`WEAPON_DOUBLEACTION`] = 'Wrench',
    [`WEAPON_REVOLVER_MK2`] = 'Wrench',
    [`WEAPON_SNSPISTOL_MK2`] = 'Wrench',
    [`WEAPON_RAYPISTOL`] = 'Ray Pistol',
    [`WEAPON_RAYCARBINE`] = 'Ray Carbine',
    [`WEAPON_RAYMINIGUN`] = 'Ray Minigun',
    [`WEAPON_DIGISCANNER`] = 'WEAPON_DIGISCANNER',
    [`WEAPON_NAVYREVOLVER`] = 'WEAPON_NAVYREVOLVER',
    [`WEAPON_CERAMICPISTOL`] = 'WEAPON_CERAMICPISTOL',
    [`WEAPON_STONE_HATCHET`] = 'WEAPON_STONE_HATCHET',
    [`WEAPON_MILITARYRIFLE`] = 'WEAPON_MILITARYRIFLE',
    [`WEAPON_COMBATSHOTGUN`] = 'WEAPON_COMBATSHOTGUN',
    [2508868239] = 'Unk',
    [-1786099057] = 'Unk',
    [2982836145] = 'Unk',
    [-1312131151] = 'Unk',
    [3249783761] = 'Unk',
    [-1045183535] = 'Unk',
    [205991906] = 'Unk',
    [375527679] = 'Unk',
    [1119849093] = 'Unk',
}

for weaponModel,_ in pairs(cfg.weapons) do
    cfg.weapons[weaponModel].hash = GetHashKey(weaponModel)
end

cfg.noAmmoWeapons = {}

for weaponModel,weaponInfo in pairs(cfg.noAmmoWeapons) do
    if weaponInfo.ammo == "" then
        cfg.noAmmoWeapons[weaponModel] = weaponInfo.hash
    end
end

cfg.weaponHashToModels = {}

for weaponModel,weaponInfo in pairs(cfg.weapons) do
    cfg.weaponHashToModels[weaponInfo.hash] = weaponModel
end

cfg.nativeWeaponHashToModels = {}

return cfg