LVLAmmoTypes = {
    ["357 Bullets"] = {"WEAPON_GUNGNIR"},
    ["12 Gauge Bullets"] = {"WEAPON_DEADPOOLSHOTTY"},
    ["5.56 NATO"] = {"WEAPON_WINCHESTER12"},
    ["7.62 Bullets"] = {"WEAPON_GALIL", "WEAPON_SCARL", "WEAPON_AKKAL", "WEAPON_R5", "WEAPON_AKKAL", "WEAPON_MOSIN", "WEAPON_AR18", "WEAPON_AN94", "WEAPON_CHUCKY"},
    ["9mm Bullets"] = {"WEAPON_PISTOL", "WEAPON_P2011", "WEAPON_IWI", "WEAPON_EVO", "WEAPON_B23R", "WEAPON_VECTOR"},
}