local Tunnel = module("arma", "lib/Tunnel")
local Proxy = module("arma", "lib/Proxy")

ARMA = Proxy.getInterface("ARMA")
ARMAclient = Tunnel.getInterface("ARMA","ARMA_fuel")

RegisterServerEvent('ARMA:requestPlayerBankBalance')
AddEventHandler('ARMA:requestPlayerBankBalance', function()
    local user_id = ARMA.getUserId({source})
    local bank = ARMA.getBankMoney({user_id})
    local wallet = ARMA.getMoney({user_id})
    TriggerClientEvent('ARMA:setDisplayMoney', source, wallet)
    TriggerClientEvent('ARMA:setDisplayBankMoney', source, bank)
    TriggerClientEvent('ARMA:initMoney', source, wallet, bank)
end)