fx_version 'cerulean'
games {  'gta5' }

description "RP module/framework"

dependency "ghmattimysql"
dependency "arma_mysql"

ui_page "gui/index.html"

shared_scripts {
  "cfg/cfg_crypto.lua",
  "sharedcfg/*",
  "armacore/cfg/cfg_*.lua",
  "cfg/cfg_*.lua",
  "shared/*.lua",
}


-- client files
files{
  "cfg/client.lua",
  "gui/index.html",
  "gui/design.css",
  "gui/style.css",
  "gui/main.js",
  "gui/app.js",
  "gui/index.js",
  "gui/Menu.js",
  "gui/ProgressBar.js",
  "gui/WPrompt.js",
  "gui/RequestManager.js",
  "gui/SoundManager.js",
  "gui/AnnounceManager.js",
  "gui/Div.js",
  "gui/dynamic_classes.js",
  "gui/fonts/Pdown.woff",
  "gui/fonts/GTA.woff",
  "gui/stratum2-bold-webfont.ttf",
  "gui/stratum2-bold-webfont.woff",
  "gui/img/*.webp",
  'gui/sounds/*',

  'audio/sfx/resident/explosions.awc',
  'audio/sfx/resident/vehicles.awc',
  'audio/sfx/resident/weapons.awc',
  'audio/sfx/weapons_player/lmg_combat.awc',
  'audio/sfx/weapons_player/lmg_mg_player.awc',
  'audio/sfx/weapons_player/mgn_sml_am83_vera.awc',
  'audio/sfx/weapons_player/mgn_sml_am83_verb.awc',
  'audio/sfx/weapons_player/mgn_sml_sc__l.awc',
  'audio/sfx/weapons_player/ptl_50cal.awc',
  'audio/sfx/weapons_player/ptl_combat.awc',
  'audio/sfx/weapons_player/ptl_pistol.awc',
  'audio/sfx/weapons_player/ptl_px4.awc',
  'audio/sfx/weapons_player/ptl_rubber.awc',
  'audio/sfx/weapons_player/sht_bullpup.awc',
  'audio/sfx/weapons_player/sht_pump.awc',
  'audio/sfx/weapons_player/smg_micro.awc',
  'audio/sfx/weapons_player/smg_smg.awc',
  'audio/sfx/weapons_player/snp_heavy.awc',
  'audio/sfx/weapons_player/snp_rifle.awc',
  'audio/sfx/weapons_player/spl_grenade_player.awc',
  'audio/sfx/weapons_player/spl_minigun_player.awc',
  'audio/sfx/weapons_player/spl_prog_ar_player.awc',
  'audio/sfx/weapons_player/spl_railgun.awc',
  'audio/sfx/weapons_player/spl_rpg_player.awc',
  'audio/sfx/weapons_player/spl_tank_player.awc',
}


-- client scripts
client_scripts{
  "rageui/RMenu.lua",
	"rageui/menu/RageUI.lua",
	"rageui/menu/Menu.lua",
	"rageui/menu/MenuController.lua",
	"rageui/components/*.lua",
	"rageui/menu/elements/*.lua",
	"rageui/menu/items/*.lua",
	"rageui/menu/panels/*.lua",
	"rageui/menu/panels/*.lua",
	"rageui/menu/windows/*.lua",
  "lib/cl_mouse.lua",
  "lib/cl_thread.lua",
  "lib/cl_cache.lua",
  "lib/cl_util.lua",
  "cfg/atms.lua",
  "cfg/weapons.lua",
  "cfg/cfg_attachments.lua",
  "cfg/skinshops.lua",
  "cfg/cfg_peds.lua",
  "cfg/cfg_dvsa.lua",
  "lib/utils.lua",
  "client/Tunnel.lua",
  "client/Proxy.lua",
  "client/base.lua",
  "utils/*",
  "client/iplloader.lua",
  "client/gui.lua",
  "client/player_state.lua",
  "client/survival.lua",
  "client/map.lua",
  "client/identity.lua",
  "client/basic_garage.lua",
  "client/police.lua",
  "client/lockcar-client.lua",
  "client/admin.lua",
  "client/enumerators.lua",
  "client/inventory.lua",
  "client/clothing.lua",
  "client/atms.lua",
  "client/garages.lua",
  "client/adminmenu.lua",
  "client/LsCustomsMenu.lua",
  "client/LsCustoms.lua",
  "client/warningsystem.lua",
  "client/lootbags.lua",
  "client/cl_crypto.lua",
  "client/cl_*.lua",
  "armacore/client/cl_*.lua",
  "armacore/cfg/cfg_*.lua",
  "cfg/client.lua",
  -- "hotkeys/hotkeys.lua"
}
-- server scripts
server_scripts{ 
  "lib/utils.lua",
  "base.lua",
  "modules/gui.lua",
  "modules/group.lua",
  "modules/admin.lua",
  "modules/survival.lua",
  "modules/player_state.lua",
  "modules/map.lua",
  "modules/money.lua",
  "modules/inventory.lua",
  "modules/identity.lua",
  "modules/business.lua",
  "modules/item_transformer.lua",
  "modules/emotes.lua",
  "modules/police.lua",
  "modules/home.lua",
  "modules/home_components.lua",
  "modules/mission.lua",
  "modules/aptitude.lua",

  -- basic implementations
  "modules/basic_phone.lua",
  "modules/basic_atm.lua",
  "modules/basic_market.lua",
  "modules/basic_gunshop.lua",
  "modules/basic_garage.lua",
  "modules/basic_items.lua",
  "modules/basic_skinshop.lua",
  "modules/cloakroom.lua",
  "modules/paycheck.lua",
  "modules/LsCustoms.lua",
  "modules/server_commands.lua",
  "modules/warningsystem.lua",
  "modules/sv_lootbags.lua",
  "modules/sv_crypto.lua",
  "modules/sv_*.lua",
  "servercfg/*.lua",
  "armacore/modules/sv_*.lua",
  -- "modules/hotkeys.lua"
}

data_file 'AUDIO_WAVEPACK' 'audio/sfx/resident'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/weapons_player'