
local cfg = {}


cfg.groups = {
	["dev"] = {

        "dev.menu",
        "dev.spawncar",
        "dev.spawnweapon",
        "dev.deletecar",
        "dev.fixcar",

        "admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
        "admin.kick",
        "admin.nof10kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.idsabovehead",
		"admin.noclip",
			
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",

		"group.add.vipgarage",
        "group.add.founder",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.moderator",
        "group.add.trial",
        "group.add",

		"group.remove.vipgarage",
        "group.remove.founder",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.moderator",
        "group.remove.trial",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		"admin.teleport", -- [Access to Teleport to Legion etc]
	},
	["founder"] = {
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
        "admin.kick",
        "admin.nof10kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.vehmenu",
		"admin.spawnGun",
		"admin.addcar",
		"admin.idsabovehead",
		"admin.smartsigns",
		
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",

		"group.add.vipgarage",
        "group.add.founder",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.moderator",
        "group.add.trial",
        "group.add",

		"group.remove.vipgarage",
        "group.remove.founder",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.moderator",
        "group.remove.trial",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		
		"vehicle.delete",
		"admin.teleport", -- [Access to Teleport to Legion etc]
	},
	["staffmanager"] = {
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
        "admin.kick",
        "admin.nof10kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.nhsAddGroups",

        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.moderator",
        "group.add.trial",

		"group.remove.vipgarage",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.moderator",
        "group.remove.trial",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		"admin.teleport", -- [Access to Teleport to Legion etc]
	},
	["commanager"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.getgroups",
	"admin.spectate",
	"admin.screenshot",
	"admin.slap",
	"admin.givemoney",
	"admin.tp2waypoint",
	"admin.tp2coords",
	"admin.removewarn",
	"admin.spawnBmx",
	"admin.noclip",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
		
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.nhsAddGroups",

	"group.add.headadmin",
	"group.add.senioradmin",
	"group.add.administrator",
	"group.add.moderator",
	"group.add.trial",

	"group.remove.headadmin",
	"group.remove.senioradmin",
	"group.remove.administrator",
	"group.remove.moderator",
	"group.remove.trial",
	"group.remove",
	
	"admin.whitelisted",
	"admin.tickets",
	"admin.teleport", -- [Access to Teleport to Legion etc]
	  },
	["headadmin"] = {
	"admin.menu",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.spectate",
    "admin.screenshot",
    "admin.slap",
    "admin.tp2waypoint",
    "admin.tp2coords",
	"admin.removewarn",
	"admin.spawnBmx",
	"admin.noclip",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
	
	"admin.whitelisted",
	"admin.tickets",
	"admin.teleport", -- [Access to Teleport to Legion etc]
  },
  ["senioradmin"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.spectate",
	"admin.screenshot",
	"admin.slap",
	"admin.tp2waypoint",
	"admin.tp2coords",
	"admin.removewarn",
	"admin.spawnBmx",
	"admin.noclip",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
	
	"admin.whitelisted",
	"admin.tickets",
	"admin.teleport", -- [Access to Teleport to Legion etc]
  },
  ["administrator"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.spectate",
	"admin.screenshot",
	"admin.slap",
	"admin.tp2waypoint",
	"admin.tp2coords",

	"admin.whitelisted",
	"admin.tickets",
	"admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
	"admin.teleport", -- [Access to Teleport to Legion etc]
  },
  ["srmoderator"] = {
    "admin.menu",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.screenshot",

    "admin.whitelisted",
    "admin.tickets",
    "admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
	"admin.teleport", -- [Access to Teleport to Legion etc]
    },
  ["moderator"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.screenshot",
		
	"admin.spectate",

	"admin.whitelisted",
	"admin.tickets",
	"admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
	"admin.teleport", -- [Access to Teleport to Legion etc]
  },
  ["supportteam"] = {
    "admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.whitelisted",
	"admin.tickets",
	"admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
	"admin.teleport", -- [Access to Teleport to Legion etc]
  },
  ["trialstaff"] = {
    "admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.kick",
	"admin.nof10kick",
	"admin.summon",
	"admin.freeze",
	"admin.whitelisted",
	"admin.tickets",
	"admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
  },

}

-- groups are added dynamically using the API or the menu, but you can add group when an user join here
cfg.users = {
  [1] = { -- give superadmin and admin group to the first created user on the database
    "founder",
    "dev",
  }
}

-- group selectors
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {}

return cfg
